### ISSUE TITLE
about package

### ISSUE THREAD

**Issue by detail662** [WillDreamer/Aurora#10]
Great Job! When I run the code and I find that I don't have this package, how can I get it？
![image](https://github.com/WillDreamer/Aurora/assets/151705775/756be8b0-6b29-4690-91ff-3583dacf3670)
![image](https://github.com/WillDreamer/Aurora/assets/151705775/dbc28b85-2346-434b-b246-9e4c98db4ce1)

**Comment by xinlong-yang** [comment]
thanks, you can delete it and we have updated the code.
