### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by BinhuiXie** [WillDreamer/Aurora#7]
there's no adapter in Aurora, is there?

shall we delete the following lines?

https://github.com/WillDreamer/Aurora/blob/6ef56f188b4d4d09b4fef375d259a18feee9b10f/CP/vit.py#L138-L139

**Comment by Arsiuuu** [comment]
Just delete this or add `adapter_visual: False` in the config.

**Comment by BinhuiXie** [comment]
> Just delete this or add `adapter_visual: False` in the config.

yup

**Comment by xinlong-yang** [comment]
yes, you can delete it.
