### ISSUE TITLE
About the Visualization

### ISSUE THREAD

**Issue by Pefect96** [WillDreamer/Aurora#9]
Great Job! May I ask how to obtain the visualization results in Figure 5?

**Comment by xinlong-yang** [comment]
Thanks, this is actually a very common visualization method, specifically, you can refer to this repo: https://github.com/salesforce/ALBEF/tree/main , the relevant code is in [visualization.ipynb](https://github.com/salesforce/ALBEF/blob/main/visualization.ipynb)
